---
abstract: 'Alias for Log::Any::For::Builtins'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  File::Which: 0
  File::chdir: 0
  Module::Build: 0.3601
  Test::More: 0.96
  UUID::Random: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Builtin-Logged
requires:
  Exporter::Lite: 0
  SHARYANTO::Proc::ChildError: 0
  SHARYANTO::String::Util: 0.19
  parent: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Builtin-Logged/
  repository: http://github.com/sharyanto/perl-Builtin-Logged
version: 0.03
